import type { AccountPreferences, AppSettings, AppSettingsPatch, Bootstrap, QueryInput, UsageAnalysis, UsagePage, UsageRange, UsageRecord, UsageSnapshot, UsageTotals } from './types'
const blank = (): UsageTotals => ({ actualCost: 0, requests: 0, inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheCreationTokens: 0 })
let range: UsageRange = 'today'
const settings: AppSettings = { theme: 'light', opacity: 1, alwaysOnTop: true, recentRefreshSeconds: 10, summaryRefreshSeconds: 30, backgroundRefreshSeconds: 120 }
const data: Bootstrap = { generation: 0, activeAccountId: 'home', range, settings, snapshot: null, accounts: [
  { id: 'home', alias: '自建站', siteUrl: 'https://home.example.com', email: 'me@example.com', role: 'admin', sessionStatus: 'ready', preferences: { defaultRange: 'today', metrics: ['cost', 'requests', 'tokens', 'cache'], recentMinutes: 5, timezone: 'Asia/Shanghai' } },
  { id: 'upstream', alias: '上游套餐', siteUrl: 'https://upstream.example.com', email: 'me@example.com', role: 'user', sessionStatus: 'ready', preferences: { defaultRange: 'week', metrics: ['balance', 'cost', 'tokens', 'cache'], recentMinutes: 5, timezone: 'Asia/Shanghai' } },
] }
function rows(id: string): UsageRecord[] { return Array.from({ length: 64 }, (_, i) => ({ id: String(6400 - i), model: i % 3 ? 'gpt-5.4' : 'claude-sonnet-4-6', keyId: String(i % 2 + 1), keyName: i % 2 ? '个人工具' : '工作电脑', createdAt: new Date(Date.now() - i * 44000 - 12000).toISOString(), actualCost: (id === 'upstream' ? .186 : .024) * (1 + i % 7 / 5), requests: 1, inputTokens: 2400 + i * 11, outputTokens: 800 + i * 7, cacheReadTokens: 9600, cacheCreationTokens: i % 3 ? 0 : 400, durationMs: 3420 + i * 100 })) }
function sum(items: UsageRecord[]): UsageTotals { return items.reduce((a, v) => { (Object.keys(a) as (keyof UsageTotals)[]).forEach(k => { a[k] += v[k] }); return a }, blank()) }
function snapshot(): UsageSnapshot | null { const account = data.accounts.find(a => a.id === data.activeAccountId); if (!account) return null; const list = rows(account.id); const end = new Date(); const start = new Date(end); if (range === 'today') start.setHours(0, 0, 0, 0); else if (range === 'month') { start.setDate(1); start.setHours(0, 0, 0, 0) } else start.setTime(+end - (range === 'week' ? 168 * 60 : account.preferences.recentMinutes) * 60000); const filtered = range === 'recent' ? list.filter(r => +new Date(r.createdAt) >= +start) : list; return { accountId: account.id, generation: 1, range, start: start.toISOString(), end: end.toISOString(), totals: sum(filtered), recent: sum(list.filter(r => +new Date(r.createdAt) >= Date.now() - account.preferences.recentMinutes * 60000)), latest: list[0]!, balance: account.id === 'upstream' ? 128.75 : 86.5, balanceUpdatedAt: end.toISOString(), usageUpdatedAt: end.toISOString(), status: 'ready' } }
function state(): Bootstrap { data.generation++; data.range = range; data.snapshot = snapshot(); return structuredClone(data) }
export const demoApi = {
  async bootstrap() { return state() },
  async switchAccount(id: string) { data.activeAccountId = id; range = data.accounts.find(a => a.id === id)!.preferences.defaultRange; return state() },
  async refresh(_id: string, r: UsageRange) { range = r; return state() },
  async savePreferences(id: string, preferences: AccountPreferences, alias: string) { const a = data.accounts.find(a => a.id === id)!; a.preferences = structuredClone(preferences); a.alias = alias; if (id === data.activeAccountId) range = preferences.defaultRange; return state() },
  async patchSettings(patch: AppSettingsPatch, expected?: AppSettingsPatch) {
    const fields = Object.keys(patch) as (keyof AppSettings)[]
    if (expected && fields.some(field => expected[field] === undefined || expected[field] !== data.settings[field])) throw new Error('应用设置已在其他入口修改，请重新确认后保存。')
    data.settings = { ...data.settings, ...patch }
    return state()
  },
  async removeAccount(id: string) { data.accounts = data.accounts.filter(a => a.id !== id); if (id === data.activeAccountId) data.activeAccountId = data.accounts[0]?.id || null; return state() },
  async logout(id: string) { const a = data.accounts.find(a => a.id === id); if (a) a.sessionStatus = 'needsLogin'; return state() },
  async records(query: QueryInput): Promise<UsagePage> { let list = rows(query.accountId).filter(r => (!query.model || r.model.includes(query.model)) && (!query.keyId || r.keyId === query.keyId)); if (query.range === 'recent') list = list.filter(r => +new Date(r.createdAt) >= Date.now() - (data.accounts.find(a => a.id === query.accountId)?.preferences.recentMinutes || 5) * 60000); return { accountId: query.accountId, generation: 1, total: list.length, page: query.page, pageSize: query.pageSize, items: list.slice((query.page - 1) * query.pageSize, query.page * query.pageSize), complete: true } },
  async analysis(accountId: string, r: UsageRange): Promise<UsageAnalysis> { const sample = snapshot(); if (!sample) throw new Error('没有示例账号'); const list = (await this.records({ accountId, range: r, page: 1, pageSize: 1000 })).items; const groups = (key: 'model' | 'keyName') => [...new Set(list.map(i => i[key]))].map(name => ({ name, ...sum(list.filter(i => i[key] === name)) })); return { accountId, generation: 1, range: r, start: sample.start, end: sample.end, timezone: data.accounts.find(a => a.id === accountId)!.preferences.timezone, syncedAt: new Date().toISOString(), complete: true, trend: Array.from({ length: 7 }, (_, i) => ({ label: `${String(8 + i).padStart(2, '0')}:00`, actualCost: sum(list.filter((_, j) => j % 7 === i)).actualCost })), models: groups('model'), keys: groups('keyName') } },
}
